# frozen_string_literal: true

require_relative 'rails_mmd/version'
require_relative 'rails_mmd/key_tuple'
require_relative 'rails_mmd/association_binding_resolver'
require_relative 'rails_mmd/relationship_id_codec'
require_relative 'rails_mmd/config'
require_relative 'rails_mmd/domain_resolver'
require_relative 'rails_mmd/model_inventory'
require_relative 'rails_mmd/rails_loader'
require_relative 'rails_mmd/relationship_builder'
require_relative 'rails_mmd/ir_builder'
require_relative 'rails_mmd/render_plan_builder'
require_relative 'rails_mmd/mermaid_serializer'
require_relative 'rails_mmd/publisher'
require_relative 'rails_mmd/generate'
require_relative 'rails_mmd/schema_probe'
